#!/bin/bash

function check_command() {
  local COMMAND="$1"
  command -v "$COMMAND" > /dev/null 2>&1 || {
    echo >&2 "$COMMAND not found."
    exit 1
  }
}

check_command awk
check_command column
check_command fzf
check_command grep
check_command sed
check_command shuf
check_command sort
check_command tr
check_command uniq
check_command wc

filename="$HOME/.todo"

test -e "$filename" || touch "$filename"

function add_todo() {
  cat <<EOF > /tmp/todo.txt
Status: todo
Created: $(date +%Y-%m-%d)
RVUs: 1
Category: uncategorized
Name: 
EOF

  $EDITOR /tmp/todo.txt

  if [ -s /tmp/todo.txt ]; then
    sed 's/.\+: //g' < /tmp/todo.txt | \
      tr '\n' '\t' | \
      sed 's/\t$/\n/g' >> "$filename"
    echo "Added to $filename"
  else
    echo "No changes made"
  fi
}

if [ $# -eq 0 ]; then
  add_todo
  exit 0
fi

function usage() {
  cat <<EOF
Usage: $0 <command>

Commands:
EOF
  cat << EOF | column -t -s '	' | sort
  add	Add a new todo
  categories	List categories
  edit	Edit todo file
  help	Show this help
  oldest	Show oldest todo
  random <n>	Show random todo
  rvus	Sum rvus
  search	Search todos
  show	Show all todos that aren't complete
  summary	Show todo summary
EOF
  exit 1
}

case "$1" in
  help)
    usage
    ;;
  add)
    add_todo
    ;;
  categories)
    awk '/^todo/{print $4}' "$filename" | \
      sort | \
      uniq -c
    ;;
  random)
    number=1

    if [ $# -eq 2 ]; then
      number="$2"
    fi

    grep "^todo" "$filename" | shuf -n "$number"
    ;;
  show)
    sed '/^done	/d' "$filename" | column -t -s $'\t' | sort
    ;;
  rvus)
    awk '
      BEGIN {sum=0}
      /^done/ {sum+=$3}
      END {print sum}
    ' "$filename"
    ;;
  search)
    fzf --preview 'echo {}' < "$filename"
    ;;
  edit)
    $EDITOR "$filename"
    ;;
  oldest)
    grep "^todo" "$filename" | sort | head -n 1 | awk 'BEGIN {FS="\t"} {print $5}'
    ;;
  summary)
    echo "Summary"
    echo "-------"
    echo "Total: $(wc -l < "$filename")"
    echo "Completed: $(grep -c "^done" "$filename")"
    echo "Pending: $(grep -c "^todo" "$filename")"
    echo "Other: $(grep -cv "^todo\|^done" "$filename")"
    ;;
  *)
    echo "Invalid command"
    echo
    usage
    ;;
esac
